#!/usr/bin/env node

//module.paths.push('C:/Users/w441/AppData/Roaming/npm/node_modules');
var express = require('express');
var app = express();
module.exports = app;
var fs = require('fs');
var http = require('http');
var https = require('BackEnd/deleted/https_deleted');
var privateKey  = fs.readFileSync('./certificate/private.pem', 'utf8');
var certificate = fs.readFileSync('./certificate/file.crt', 'utf8');
var credentials = {key: privateKey, cert: certificate};

var httpServer = http.createServer(app);
var httpsServer = https.createServer(credentials, app);
var PORT = 8430;
var SSLPORT = 8431;

httpServer.listen(PORT, function() {
    console.log('HTTP Server is running on: http://localhost:%s', PORT);
});
httpsServer.listen(SSLPORT, function() {
    console.log('HTTPS Server is running on: https://localhost:%s', SSLPORT);
});

// Welcome
app.get('/', function(req, res) {
    if(req.protocol === 'https') {
        res.status(200).send('Welcome! https');
    }
    else {
        res.status(200).send('Welcome! http');
    }
});