<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_icon</name>
   <tag></tag>
   <elementGuidId>0c7efb91-5a9b-4e5a-bd11-f2be3bb1a1db</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/blackheart_trans_bg.ico</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;todolist&quot;)/fieldset[@class=&quot;form-group py-0 my-0&quot;]/ul[@class=&quot;nav nav-tabs nav-justified indigo&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]/img[@class=&quot;icon&quot;]</value>
   </webElementProperties>
</WebElementEntity>
