<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pre_user_id10e78428-4f85-11e8-</name>
   <tag></tag>
   <elementGuidId>e7917dfd-41ec-46fb-ac13-853643785a1a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>pre</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>{&quot;user_id&quot;:&quot;10e78428-4f85-11e8-8c21-02388973fed8&quot;,&quot;token&quot;:&quot;eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwZTc4NDI4LTRmODUtMTFlOC04YzIxLTAyMzg4OTczZmVkOCIsImlhdCI6MTUyNjg2NTU1NywiZXhwIjoxNTI2OTUxOTU3fQ.EVFh3TaF5giXWecbEeEWlyEm-eZ5zo1W__igGnD6GpQ&quot;}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/pre[1]</value>
   </webElementProperties>
</WebElementEntity>
